# Sources:
# https://gist.github.com/vidavidorra/548ffbcdae99d752da02
# http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/      

#blacklist
branches:
        except:
        - gh-pages

env:
        global:
        - GITHUB_REPO: pfcrender
        - DOXYFILE: $TRAVIS_BUILD_DIR/bin/doc/Doxyfile

#additional deps
addons:
        apt:
                sources:
                        - boost-latest
                packages:
                #docs
                - doxygen
                - doxygen-doc
                - doxygen-latex
                - doxygen
                - graphviz
                #unit testing w CUTE
                - libboost1.55-all-dev
                #build
                - cmake

language: cpp
compiler:
        - gcc
        - clang++

script: cd bin && cmake .. && make && make test

os:
        - linux
        - osx

#Generated doxygen docs and put in gh_pages
after_success:
        - bash ../doc/deploy-doxygen-to-gh-pages.sh
