# Sources:
# https://gist.github.com/vidavidorra/548ffbcdae99d752da02
# http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/      

#use trusty distro for C++11 and cmake 3+
dist: trusty
sudo: require


#blacklist
branches:
  except:
  - gh-pages

env:
  global:
  - GITHUB_REPO: pfcrender


#additional deps
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    #docs
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen
    - graphviz
    #build
    - cmake

language: C++
compiler:
        - gcc
        - clang++

os:
        - linux
        - osx

before_install:
  # C++14
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  # Qt5.9
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then travis_retry sudo add-apt-repository ppa:beineri/opt-qt592-trusty -y ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then travis_retry sudo apt-get update -qq ; fi
  #coverage - lcov for gcc5
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/l/lcov/lcov_1.13-3_all.deb
  - sudo dpkg -i lcov_1.13-3_all.deb

install:
  # C++14
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then travis_retry sudo apt-get install -qq g++-5 ; fi
  # g++ should call g++-5
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then travis_retry sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90 ; fi
  #Qt5.9
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then travis_retry travis_wait sudo apt-get install qt59-meta-full ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then source /opt/qt59/bin/qt59-env.sh ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]] ; then travis_retry brew update ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]] ; then brew install qt5 ; fi

#emulate x server to run the gui on linux - necessary for testing 
before_script:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then export DISPLAY=:99.0 ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then sh -e /etc/init.d/xvfb start ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then sleep 3 ; fi # give xvfb some time to start

script: 
  - if [[ $TRAVIS_OS_NAME == 'linux' && $CXX != 'g++' ]] ; then cd bin && cmake .. && make && ctest -V ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' && $CXX == 'g++' ]] ; then cd bin && cmake -DCMAKE_BUILD_TYPE=Coverage -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 .. && make VERBOSE=1 && ctest -V ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]] ; then cd bin && cmake .. && make && ctest -V ; fi

#On successful build of master branch regenerate doxygen docs and publish on Github Pages, upload gcov results to coveralls
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash $TRAVIS_BUILD_DIR/doc/deploy-doxygen-to-gh-pages.sh
  - if [[ $TRAVIS_OS_NAME == 'linux' && $CXX == 'g++' ]] ; then lcov --directory . --capture --no-external --output-file coverage.info && lcov --remove coverage.info '*_autogen/*' --output-file coverage.info && lcov --list coverage.info && bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports" ; fi




