language: cpp
compiler:
        - gcc
        - clang++
addons:
        apt:
                sources:
                        - boost-latest
                        - george-edison55-precise-backports
                packages:
                        - libboost1.55-all-dev
                        - cmake
                        - cmake-data
                        - libqt5-devel
script: cd bin && cmake .. && make && make test
os:
        - linux
        - osx
