# Sources:
# https://gist.github.com/vidavidorra/548ffbcdae99d752da02
# http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/      

#blacklist
branches:
        except:
        - gh-pages

env:
        global:
        - GITHUB_REPO: pfcrender

#additional deps
addons:
        apt:
                packages:
                #docs
                - doxygen
                - doxygen-doc
                - doxygen-latex
                - doxygen
                - graphviz
                #build
                - cmake

language: cpp
compiler:
        - gcc
        - clang++

script: cd bin && cmake .. && make && make test

os:
        - linux
        - osx

#On successful build of master branch regenerate doxygen docs and publish on Github Pages 
after_success:
        - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash $TRAVIS_BUILD_DIR/doc/deploy-doxygen-to-gh-pages.sh
