dist: trusty
sudo: required

language: cpp
compiler:
        - gcc
        - clang++
addons:
        apt:
                sources:
                        - boost-latest
                packages:
                        - libboost1.55-all-dev
                        - libqt5-devel
                        - cmake
script: cd bin && cmake .. && make && make test
os:
        - linux
        - osx
