# Sources: https://gist.github.com/vidavidorra/548ffbcdae99d752da02

#blacklist
branches:
        except:
        - gh-pages

env:
        global:
        - GH_NAME: pfcrender
        - GH_REF: github.com/garandor/pfcrender.git
        - DOXYFILE: $TRAVIS_BUILD_DIR/bin/doc/Doxyfile

#additional deps
addons:
        apt:
                sources:
                        - boost-latest
                packages:
                #docs
                - doxygen
                - doxygen-doc
                - doxygen-latex
                - doxygen
                - graphviz
                #unit testing w CUTE
                - libboost1.55-all-dev
                #build
                - cmake

language: cpp
compiler:
        - gcc
        - clang++

script: cd bin && cmake .. && make && make test
os:$TRAVIS_BUILD_DIR/<path_to_your_doxygen_configuration_file>
        - linux
        - osx

#Generated doxygen docs and put in gh_pages
after_success:
        - doxygen $DOXYFILE
        - git add --all 
        - git commit -m "Deploy code docs to GitHub Pages Travis build: ${TRAVIS_BUILD_NUMBER}" -m "Commit: ${TRAVIS_COMMIT}"
        - git push "https://${GH_REPO_TOKEN}@${GH_REPO_REF}" > /dev/null 2>&1
