# Sources:
# https://gist.github.com/vidavidorra/548ffbcdae99d752da02
# http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/      

#use trusty distro for C++11 and cmake 3+
dist: trusty
sudo: required


#blacklist
branches:
        except:
        - gh-pages

env:
        global:
        - GITHUB_REPO: pfcrender
        - QT_ROOT: 'usr/local/qt5'

#additional deps
addons:
        apt:
                packages:
                #docs
                - doxygen
                - doxygen-doc
                - doxygen-latex
                - doxygen
                - graphviz
                #build
                - cmake

language: cpp
compiler:
        - gcc
        - clang++

os:
        - linux
        - osx

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then sudo apt-get update ; fi

install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then sudo apt-get install qt59-meta-full ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]] ; then source /opt/qt59/bin/qt59-env.sh ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]] ; then brew install qt5 ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]] ; then brew link qt5 --force ; fi

script: 
  - cd bin && cmake .. && make && make test

#On successful build of master branch regenerate doxygen docs and publish on Github Pages 
after_success:
        - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash $TRAVIS_BUILD_DIR/doc/deploy-doxygen-to-gh-pages.sh
