var annotated =
[
    [ "Common", "namespaceCommon.html", "namespaceCommon" ],
    [ "Model", "namespaceModel.html", "namespaceModel" ],
    [ "Plugins", "namespacePlugins.html", "namespacePlugins" ],
    [ "QtCLI", "namespaceQtCLI.html", "namespaceQtCLI" ],
    [ "QtGui", "namespaceQtGui.html", null ],
    [ "QtGUI", "namespaceQtGUI.html", "namespaceQtGUI" ],
    [ "util", "namespaceutil.html", "namespaceutil" ],
    [ "Plugin_Registry", "classPlugin__Registry.html", null ],
    [ "QNanoQuickItem", "classQNanoQuickItem.html", null ],
    [ "QNanoQuickItemPainter", "classQNanoQuickItemPainter.html", null ],
    [ "QObject", "classQObject.html", null ],
    [ "qt_meta_stringdata_Model__LSYSModel_t", "structqt__meta__stringdata__Model____LSYSModel__t.html", "structqt__meta__stringdata__Model____LSYSModel__t" ],
    [ "qt_meta_stringdata_Model__LSYSModelImpl_t", "structqt__meta__stringdata__Model____LSYSModelImpl__t.html", "structqt__meta__stringdata__Model____LSYSModelImpl__t" ],
    [ "qt_meta_stringdata_Plugins__Export__PDF__PDF_t", "structqt__meta__stringdata__Plugins____Export____PDF____PDF__t.html", "structqt__meta__stringdata__Plugins____Export____PDF____PDF__t" ],
    [ "qt_meta_stringdata_Plugins__Export__Stdout__StdoutExport_t", "structqt__meta__stringdata__Plugins____Export____Stdout____StdoutExport__t.html", "structqt__meta__stringdata__Plugins____Export____Stdout____StdoutExport__t" ],
    [ "qt_meta_stringdata_Plugins__Export__SVG__SVG_t", "structqt__meta__stringdata__Plugins____Export____SVG____SVG__t.html", "structqt__meta__stringdata__Plugins____Export____SVG____SVG__t" ],
    [ "qt_meta_stringdata_Plugins__Exporter_t", "structqt__meta__stringdata__Plugins____Exporter__t.html", "structqt__meta__stringdata__Plugins____Exporter__t" ],
    [ "qt_meta_stringdata_Plugins__Import_t", "structqt__meta__stringdata__Plugins____Import__t.html", "structqt__meta__stringdata__Plugins____Import__t" ],
    [ "qt_meta_stringdata_Plugins__LSYS__LSYS_t", "structqt__meta__stringdata__Plugins____LSYS____LSYS__t.html", "structqt__meta__stringdata__Plugins____LSYS____LSYS__t" ],
    [ "qt_meta_stringdata_Plugins__Plugin_t", "structqt__meta__stringdata__Plugins____Plugin__t.html", "structqt__meta__stringdata__Plugins____Plugin__t" ],
    [ "qt_meta_stringdata_QNanoQuickItem_t", "structqt__meta__stringdata__QNanoQuickItem__t.html", "structqt__meta__stringdata__QNanoQuickItem__t" ],
    [ "qt_meta_stringdata_QtCLI__PFCRenderCLI_t", "structqt__meta__stringdata__QtCLI____PFCRenderCLI__t.html", "structqt__meta__stringdata__QtCLI____PFCRenderCLI__t" ],
    [ "qt_meta_stringdata_QtGUI__PFCRenderGUI_t", "structqt__meta__stringdata__QtGUI____PFCRenderGUI__t.html", "structqt__meta__stringdata__QtGUI____PFCRenderGUI__t" ],
    [ "qt_meta_stringdata_QtGUI__QNanoCurvePainter_t", "structqt__meta__stringdata__QtGUI____QNanoCurvePainter__t.html", "structqt__meta__stringdata__QtGUI____QNanoCurvePainter__t" ],
    [ "qt_meta_stringdata_QtGUI__QNanoPaintedCurve_t", "structqt__meta__stringdata__QtGUI____QNanoPaintedCurve__t.html", "structqt__meta__stringdata__QtGUI____QNanoPaintedCurve__t" ],
    [ "string_subst", "classstring__subst.html", "classstring__subst" ],
    [ "Test_CLI", "classTest__CLI.html", null ],
    [ "Test_GUI", "classTest__GUI.html", "classTest__GUI" ]
];