#Forked from https://github.com/fifengine/cpp-tutorials/blob/master/appveyor.yml



# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

platform:
  - x64

configuration:
  - Release
  - Debug

generator:
  - "MinGW Makefiles"
install:
  - cd bin
  - cmake -G "%generator%" ..

build_script:
  - cmake --build . --config %configuration%
  - ctest
