# scripts that are called at very beginning, before repo cloning
init:
  - cmd: msbuild /version
  - git config --global core.autocrlf input

version: '0.2.{build}'

platform:
  - x64

configuration:
  - Debug

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  matrix:
    - GENERATOR: "Visual Studio 14 2015"
      os: Visual Studio 2015

install:
  - git submodule update --init --recursive

before_build:
  - cd bin
  - cmake -G "%GENERATOR% Win64" -DCMAKE_BUILD_TYPE=%configuration% ..

build:
  project: bin/pfcrender.sln
