#Forked from https://github.com/fifengine/cpp-tutorials/blob/master/appveyor.yml

# Build worker image (VM template)
image: Visual Studio 2013

# scripts that are called at very beginning, before repo cloning
init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

version: '{build}'

platform:
  - x64

configuration:
  - Release
  - Debug

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
    - generator: "Visual Studio 12 2013"

matrix:
  fast_finish: true

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%/bin
  # generate build script
  - >
    cmake %APPVEYOR_BUILD_FOLDER%
    -G "%generator%" 
  # build
  - cmake --build . --target ALL_BUILD --config %configuration% -- /nologo /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  # install
  - cmake --build . --target INSTALL --config %configuration% -- /nologo
