pfcrender: QtCLI::PFCRenderCLI Class Reference
QtCLI::PFCRenderCLI Class Reference
The PFCRenderCLI class This class is used when –batch operation is requested and execute the sequence.
#include <PFCRenderCLI.h>
Public Member Functions
PFCRenderCLI (LSYSModel &)
~PFCRenderCLI ()
Detailed Description
The PFCRenderCLI class This class is used when –batch operation is requested and execute the sequence.
Constructor & Destructor Documentation
QtCLI::PFCRenderCLI::PFCRenderCLI (LSYSModel & mdl)
References Common::Sequence_Walker::execute().
QtCLI::PFCRenderCLI::~PFCRenderCLI ()
References Common::Plugin_Registry::getInstance(), and Common::Config_Registry::getInstance().
The documentation for this class was generated from the following files:
src/QtCLI/PFCRenderCLI.h
src/QtCLI/PFCRenderCLI.cpp