pfcrender: Plugins::Export::PDF::PDF Class Reference
Plugins::Export::PDF::PDF Class Reference
The PDF class An exporter for PDFs Fits a model to an A4 page and prints to PDF.
#include <pdf.h>
Public Member Functions
PDF ()
virtual ~PDF ()
const Plugins::PluginInfo & getInfo () const override
void exportModel (const ::Model::LSYSModel &mdl) const override
runs the export plugin
Public Member Functions inherited from Plugins::Exporter
virtual ~Exporter ()
Public Member Functions inherited from Plugins::Plugin
virtual ~Plugin ()
Private Member Functions
void printPDF (const Model::LSYSModel &mdl) const
Private Attributes
PluginInfo m_info
Detailed Description
The PDF class An exporter for PDFs Fits a model to an A4 page and prints to PDF.
Todo:
Make page characteristis user selectable
Constructor & Destructor Documentation
Plugins::Export::PDF::PDF::PDF ()
References Plugins::PluginInfo::co, Plugins::PluginInfo::conf_opts, Plugins::PluginInfo::desc, m_info, Plugins::PluginInfo::name, and Plugins::PluginInfo::plugin.
virtual Plugins::Export::PDF::PDF::~PDF () inline virtual
Member Function Documentation
void Plugins::Export::PDF::PDF::exportModel (const ::Model::LSYSModel &) const override virtual
runs the export plugin
Returns
void
Implements Plugins::Exporter.
References printPDF().
const Plugins::PluginInfo & Plugins::Export::PDF::PDF::getInfo () const override virtual
Implements Plugins::Plugin.
References m_info.
void Plugins::Export::PDF::PDF::printPDF (const Model::LSYSModel & mdl) const private
References Plugins::Export::BboxParse::getBbox(), Common::Config_Registry::getInstance(), Model::LSYSModel::getModel(), and Common::Config_Registry::getOpt().
Referenced by exportModel().
Member Data Documentation
PluginInfo Plugins::Export::PDF::PDF::m_info private
Referenced by getInfo(), and PDF().
The documentation for this class was generated from the following files:
src/Plugins/PDF/pdf.h
src/Plugins/PDF/pdf.cpp