pfcrender: QtGUI::QNanoPaintedCurve Class Reference
QtGUI::QNanoPaintedCurve Class Reference
The QNanoPaintedCurve class This class is the GUI interface to the item placed in the rendering scene and handles business logic related to drawing.
#include <QNanoPaintedCurve.h>
Public Slots
void onConfigChanged ()
void onModelChanged (QString const *pstr)
void onBoundingBoxChanged (QRectF newBox)
Signals
void boundingBoxChanged (QRectF newBox)
Public Member Functions
QNanoPaintedCurve (QQuickItem *parent=0)
QNanoQuickItemPainter * createItemPainter () const
Private Attributes
QString const * p_mdl
bool drawing_params_changed = false
Friends
class QtGUI::QNanoCurvePainter
Detailed Description
The QNanoPaintedCurve class This class is the GUI interface to the item placed in the rendering scene and handles business logic related to drawing.
Constructor & Destructor Documentation
QtGUI::QNanoPaintedCurve::QNanoPaintedCurve (QQuickItem * parent = 0) inline
Member Function Documentation
void QtGUI::QNanoPaintedCurve::boundingBoxChanged (QRectF newBox) signal
Referenced by onBoundingBoxChanged().
QNanoQuickItemPainter * QtGUI::QNanoPaintedCurve::createItemPainter () const
References QtGUI::QNanoCurvePainter::boundingBoxChanged(), and onBoundingBoxChanged().
void QtGUI::QNanoPaintedCurve::onBoundingBoxChanged (QRectF newBox) inline slot
References boundingBoxChanged().
Referenced by createItemPainter().
void QtGUI::QNanoPaintedCurve::onConfigChanged () inline slot
References drawing_params_changed.
void QtGUI::QNanoPaintedCurve::onModelChanged (QString const * pstr) slot
References drawing_params_changed, and p_mdl.
Friends And Related Function Documentation
friend class QtGUI::QNanoCurvePainter friend
Member Data Documentation
bool QtGUI::QNanoPaintedCurve::drawing_params_changed = false private
Referenced by onConfigChanged(), onModelChanged(), and QtGUI::QNanoCurvePainter::synchronize().
QString const* QtGUI::QNanoPaintedCurve::p_mdl private
Referenced by onModelChanged().
The documentation for this class was generated from the following files:
src/QtGUI/QNanoPaintedCurve.h
src/QtGUI/QNanoPaintedCurve.cpp
src/pfcrender_autogen/LTFMYGGEGO/moc_QNanoPaintedCurve.cpp