pfcrender: util::PolarVector2D Class Reference
util::PolarVector2D Class Reference
The PolarVector2D class utility class for easy calculation of vertex coordinates, iteration of the curve can be done by manipulating the current object, avoiding potentially costly copying.
#include <PolarVector2D.h>
Public Member Functions
PolarVector2D ()
PolarVector2D & next ()
const QSGGeometry::ColoredPoint2D & getPoint ()
void addToAngle (qreal inc)
void setColor (const QColor &c)
const QColor getColor () const
operator QPointF ()
Public Attributes
QSGGeometry::ColoredPoint2D start
qreal angle
qreal length
Detailed Description
The PolarVector2D class utility class for easy calculation of vertex coordinates, iteration of the curve can be done by manipulating the current object, avoiding potentially costly copying.
Constructor & Destructor Documentation
util::PolarVector2D::PolarVector2D () inline
Member Function Documentation
void util::PolarVector2D::addToAngle (qreal inc) inline
References angle.
Referenced by Plugins::Export::PDF::QPainterParse::decAngle(), Plugins::Export::SVG::QPainterParse::decAngle(), Plugins::Export::BboxParse::decAngle(), Plugins::Export::SVG::QPainterParse::incAngle(), Plugins::Export::PDF::QPainterParse::incAngle(), and Plugins::Export::BboxParse::incAngle().
const QColor util::PolarVector2D::getColor () const inline
References start.
const QSGGeometry::ColoredPoint2D& util::PolarVector2D::getPoint () inline
References start.
PolarVector2D& util::PolarVector2D::next () inline
References angle, length, and start.
Referenced by Plugins::Export::PDF::QPainterParse::add_segment(), Plugins::Export::SVG::QPainterParse::add_segment(), and Plugins::Export::BboxParse::add_segment().
util::PolarVector2D::operator QPointF () inline
References start.
void util::PolarVector2D::setColor (const QColor & c) inline
References start.
Member Data Documentation
qreal util::PolarVector2D::angle
Referenced by addToAngle(), and next().
qreal util::PolarVector2D::length
Referenced by next().
QSGGeometry::ColoredPoint2D util::PolarVector2D::start
Referenced by Plugins::Export::BboxParse::add_segment(), getColor(), getPoint(), next(), operator QPointF(), and setColor().
The documentation for this class was generated from the following file:
src/util/PolarVector2D.h