pfcrender: Common::Plugin_Registry Class Reference
Common::Plugin_Registry Class Reference
The Plugin_Registry singleton Holds a map of plugins and their names for access from sequence walker and config_registry.
#include <Plugin_Registry.h>
Public Member Functions
Plugins::Plugin * getPlugin (const QString &pluginName) const
QList< Plugins::Plugin * > getPlugins () const
Static Public Member Functions
static Plugin_Registry * getInstance ()
Private Member Functions
Plugin_Registry ()
Private Attributes
QHash< QString, Plugins::Plugin * > m_registered
Static Private Attributes
static Plugin_Registry * instance = NULL
Detailed Description
The Plugin_Registry singleton Holds a map of plugins and their names for access from sequence walker and config_registry.
Constructor & Destructor Documentation
Plugin_Registry::Plugin_Registry () private
Referenced by getInstance().
Member Function Documentation
Plugin_Registry * Plugin_Registry::getInstance () static
References instance, and Plugin_Registry().
Referenced by Common::Config_Registry::add_to_sequence(), Plugins::LSYS::LSYSModelFactory::createModel(), Common::Sequence_Walker::execute(), QtCLI::PFCRenderCLI::~PFCRenderCLI(), and QtGUI::PFCRenderGUI::~PFCRenderGUI().
Plugins::Plugin * Plugin_Registry::getPlugin (const QString & pluginName) const
References m_registered.
QList< Plugins::Plugin * > Plugin_Registry::getPlugins () const
References m_registered.
Member Data Documentation
Plugin_Registry * Plugin_Registry::instance = NULL static private
Referenced by getInstance().
QHash<QString, Plugins::Plugin*> Common::Plugin_Registry::m_registered private
Referenced by getPlugin(), and getPlugins().
The documentation for this class was generated from the following files:
src/Common/Plugin_Registry.h
src/Common/Plugin_Registry.cpp