pfcrender: Model::LSYSModel Class Reference
Model::LSYSModel Class Reference abstract
The LSYSModel class Holds a data model string in a unique ptr, notifies and supplies clients with changes.
#include <LSYSModel.h>
Signals
virtual void modelChanged (const QString &new_string) const =0
Public Member Functions
virtual void setModel (std::unique_ptr< QString >)=0
virtual QString const * getModel () const =0
virtual ~LSYSModel ()
Detailed Description
The LSYSModel class Holds a data model string in a unique ptr, notifies and supplies clients with changes.
Constructor & Destructor Documentation
virtual Model::LSYSModel::~LSYSModel () inline virtual
Member Function Documentation
virtual QString const* Model::LSYSModel::getModel () const pure virtual
Implemented in Model::LSYSModelImpl.
Referenced by Plugins::Export::SVG::SVG::drawSVG(), Plugins::Export::Stdout::StdoutExport::exportModel(), and Plugins::Export::PDF::PDF::printPDF().
virtual void Model::LSYSModel::modelChanged (const QString & new_string) const pure virtual signal
virtual void Model::LSYSModel::setModel (std::unique_ptr< QString >) pure virtual
Implemented in Model::LSYSModelImpl.
Referenced by Common::Sequence_Walker::execute().
The documentation for this class was generated from the following file:
src/Model/LSYSModel.h