pfcrender: Common::Config_Registry Class Reference
Common::Config_Registry Class Reference
The Config_Registry singleton is a global configuration store singleton It is fed from filesystem, CLI, and GUI.
#include <Config_Registry.h>
Public Slots
const QString getOpt (const QString &optName) const
Config_Registry::getOpt.
void setOpt (const QString &optName, const QString &optValue)
void setOpt (const QPair< QString, QString > &)
Public Member Functions
~Config_Registry ()
Config_Registry::~Config_Registry Since this is a singleton class, this destructor only gets called on program end and is responsible for saving the application state.
void add_to_sequence (const QString &name)
void clearSequence ()
const QVector< QString > getSequence () const
Static Public Member Functions
static Config_Registry * getInstance ()
Private Member Functions
Config_Registry ()
void store_to_file ()
Private Attributes
QHash< QString, QString > m_options
XXX: Old style leaky singleton. Should be a more C++11 style definiton.
QVector< QString > m_sequence
QSettings m_set
Static Private Attributes
static Config_Registry * instance = nullptr
Detailed Description
The Config_Registry singleton is a global configuration store singleton It is fed from filesystem, CLI, and GUI.
Constructor & Destructor Documentation
Common::Config_Registry::Config_Registry () private
Referenced by getInstance().
Common::Config_Registry::~Config_Registry ()
Config_Registry::~Config_Registry Since this is a singleton class, this destructor only gets called on program end and is responsible for saving the application state.
References store_to_file().
Member Function Documentation
void Common::Config_Registry::add_to_sequence (const QString & name)
References Common::Plugin_Registry::getInstance(), and m_sequence.
void Common::Config_Registry::clearSequence ()
References m_sequence.
Referenced by Common::Sequence_Walker::Sequence_Walker().
Config_Registry * Common::Config_Registry::getInstance () static
References Config_Registry(), and instance.
Referenced by Plugins::LSYS::LSYSModelFactory::createModel(), Plugins::Export::SVG::SVG::drawSVG(), Test_GUI::initTestCase(), main(), Plugins::Export::PDF::QPainterParse::parsing_preamble(), Plugins::Export::SVG::QPainterParse::parsing_preamble(), QtGUI::QNanoCurvePainter::parsing_preamble(), Plugins::Export::PDF::PDF::printPDF(), Common::Sequence_Walker::Sequence_Walker(), Plugins::LSYS::Test_LSYS::test_modelstringOutputs(), QtCLI::PFCRenderCLI::~PFCRenderCLI(), and QtGUI::PFCRenderGUI::~PFCRenderGUI().
const QString Common::Config_Registry::getOpt (const QString & optName) const slot
Config_Registry::getOpt.
Parameters
optName
Returns
the value passed to this option, or an empty string
References m_options.
Referenced by Plugins::Export::SVG::SVG::drawSVG(), Plugins::Export::PDF::QPainterParse::parsing_preamble(), Plugins::Export::SVG::QPainterParse::parsing_preamble(), QtGUI::QNanoCurvePainter::parsing_preamble(), and Plugins::Export::PDF::PDF::printPDF().
const QVector< QString > Common::Config_Registry::getSequence () const
References m_sequence.
void Common::Config_Registry::setOpt (const QString & optName, const QString & optValue) slot
References m_options.
Referenced by Test_GUI::initTestCase(), and setOpt().
void Common::Config_Registry::setOpt (const QPair< QString, QString > & p) slot
References setOpt().
void Common::Config_Registry::store_to_file () private
References m_options, and m_set.
Referenced by ~Config_Registry().
Member Data Documentation
Config_Registry * Common::Config_Registry::instance = nullptr static private
Referenced by getInstance().
QHash<QString, QString> Common::Config_Registry::m_options private
XXX: Old style leaky singleton. Should be a more C++11 style definiton.
Referenced by getOpt(), setOpt(), and store_to_file().
QVector<QString> Common::Config_Registry::m_sequence private
Referenced by add_to_sequence(), clearSequence(), and getSequence().
QSettings Common::Config_Registry::m_set private
Referenced by store_to_file().
The documentation for this class was generated from the following files:
src/Common/Config_Registry.h
src/Common/Config_Registry.cpp