pfcrender: QtGUI::QNanoCurvePainter Class Reference
QtGUI::QNanoCurvePainter Class Reference
The QNanoCurvePainter class This class is executed through the scene graph from the rendering thread and draws the actual geometry. It pulls its data from QNanoPaintedCurve before drawing.
#include <QNanoCurvePainter.h>
Signals
void boundingBoxChanged (QRectF newBox)
Public Member Functions
QNanoCurvePainter ()
void paint (QNanoPainter *p) override
void synchronize (QNanoQuickItem *item) override
Private Member Functions
void parsing_preamble ()
void parsing_finalize ()
LSYS_STRING_PARSE_FUNC_DECL void add_segment ()
void next_color ()
void prev_color ()
void incAngle ()
void decAngle ()
void stackPush ()
void stackPop ()
Private Attributes
QNanoPainter * p
QString modelstring
util::PolarVector2D pos
util::PolarVector2D p1
util::PolarVector2D p2
util::PolarVector2D p3
bool is_first_segment = true
QStack< util::PolarVector2D > stack {}
int cur_color_idx
double angle
QPointF coord_final
QPointF min
QPointF max
QRectF boundingBox
double rounding
Detailed Description
The QNanoCurvePainter class This class is executed through the scene graph from the rendering thread and draws the actual geometry. It pulls its data from QNanoPaintedCurve before drawing.
Constructor & Destructor Documentation
QtGUI::QNanoCurvePainter::QNanoCurvePainter () inline
Member Function Documentation
void QtGUI::QNanoCurvePainter::add_segment () inline private
void QtGUI::QNanoCurvePainter::boundingBoxChanged (QRectF newBox) signal
Referenced by QtGUI::QNanoPaintedCurve::createItemPainter(), and paint().
void QtGUI::QNanoCurvePainter::decAngle () private
void QtGUI::QNanoCurvePainter::incAngle () private
void QtGUI::QNanoCurvePainter::next_color () private
void QtGUI::QNanoCurvePainter::paint (QNanoPainter * p) override
References boundingBox, boundingBoxChanged(), cur_color_idx, max, min, modelstring, p, parsing_finalize(), and parsing_preamble().
void QtGUI::QNanoCurvePainter::parsing_finalize () inline private
Referenced by paint().
void QtGUI::QNanoCurvePainter::parsing_preamble () inline private
TODO: Get colors from config
References Common::Config_Registry::getInstance(), and Common::Config_Registry::getOpt().
Referenced by paint().
void QtGUI::QNanoCurvePainter::prev_color () private
void QtGUI::QNanoCurvePainter::stackPop () private
void QtGUI::QNanoCurvePainter::stackPush () private
void QtGUI::QNanoCurvePainter::synchronize (QNanoQuickItem * item) override
References QtGUI::QNanoPaintedCurve::drawing_params_changed.
Member Data Documentation
double QtGUI::QNanoCurvePainter::angle private
QRectF QtGUI::QNanoCurvePainter::boundingBox private
Referenced by paint().
QPointF QtGUI::QNanoCurvePainter::coord_final private
int QtGUI::QNanoCurvePainter::cur_color_idx private
Referenced by paint().
bool QtGUI::QNanoCurvePainter::is_first_segment = true private
QPointF QtGUI::QNanoCurvePainter::max private
Referenced by paint().
QPointF QtGUI::QNanoCurvePainter::min private
Referenced by paint().
QString QtGUI::QNanoCurvePainter::modelstring private
Referenced by paint().
QNanoPainter* QtGUI::QNanoCurvePainter::p private
Referenced by paint().
util::PolarVector2D QtGUI::QNanoCurvePainter::p1 private
util::PolarVector2D QtGUI::QNanoCurvePainter::p2 private
util::PolarVector2D QtGUI::QNanoCurvePainter::p3 private
util::PolarVector2D QtGUI::QNanoCurvePainter::pos private
double QtGUI::QNanoCurvePainter::rounding private
QStack<util::PolarVector2D> QtGUI::QNanoCurvePainter::stack {} private
The documentation for this class was generated from the following files:
src/QtGUI/QNanoCurvePainter.h
src/QtGUI/QNanoCurvePainter.cpp
src/pfcrender_autogen/LTFMYGGEGO/moc_QNanoCurvePainter.cpp