pfcrender: Common::Sequence_Walker Class Reference
Common::Sequence_Walker Class Reference
The Sequence_Walker class runs the sequence given from CLI or GUI This builder style class takes steps set in config_registry and executes them.
#include <Sequence_Walker.h>
Public Member Functions
Sequence_Walker ()
void addStep (const QString &stepName)
void execute (Model::LSYSModel &mod)
Common::Sequence_Walker::execute.
Public Attributes
QVector< QString > m_stepNames
Detailed Description
The Sequence_Walker class runs the sequence given from CLI or GUI This builder style class takes steps set in config_registry and executes them.
Constructor & Destructor Documentation
Common::Sequence_Walker::Sequence_Walker ()
References addStep(), Common::Config_Registry::clearSequence(), and Common::Config_Registry::getInstance().
Member Function Documentation
void Common::Sequence_Walker::addStep (const QString & stepName)
Referenced by Sequence_Walker().
void Common::Sequence_Walker::execute (Model::LSYSModel & mod)
Common::Sequence_Walker::execute.
Parameters
mod The model to be given to modify and export plugins. Unused by import
sequence: check if step is plugin get the factory execute build put result where it belongs
References Plugins::Plugin::getInfo(), Common::Plugin_Registry::getInstance(), Plugins::PluginInfo::name, and Model::LSYSModel::setModel().
Referenced by QtCLI::PFCRenderCLI::PFCRenderCLI(), and QtGUI::PFCRenderGUI::PFCRenderGUI().
Member Data Documentation
QVector<QString> Common::Sequence_Walker::m_stepNames
Referenced by QtGUI::PFCRenderGUI::PFCRenderGUI().
The documentation for this class was generated from the following files:
src/Common/Sequence_Walker.h
src/Common/Sequence_Walker.cpp