pfcrender: Plugins::LSYS::LSYSModelFactory Class Reference
Plugins::LSYS::LSYSModelFactory Class Reference
The LSYSModelFactory class The builder implementation that will be returned from the plugin.
#include <LSYSModelFactory.h>
Public Member Functions
std::unique_ptr< QString > createModel () override
Private Member Functions
std::unique_ptr< QString > _computeLSYS (const QList< QString > &definition, const ulong iterate)
Detailed Description
The LSYSModelFactory class The builder implementation that will be returned from the plugin.
Member Function Documentation
std::unique_ptr< QString > Plugins::LSYS::LSYSModelFactory::_computeLSYS (const QList< QString > & definition, const ulong iterate) private
References string_subst::set_axiom().
Referenced by createModel().
std::unique_ptr< QString > Plugins::LSYS::LSYSModelFactory::createModel () override virtual
Implements Model::ModelStringBuilder.
References _computeLSYS(), Plugins::PluginInfo::conf_opts, Plugins::Plugin::getInfo(), Common::Plugin_Registry::getInstance(), and Common::Config_Registry::getInstance().
The documentation for this class was generated from the following files:
src/Plugins/LSYS/LSYSModelFactory.h
src/Plugins/LSYS/LSYSModelFactory.cpp