pfcrender: src/qrc_qml.cpp File Reference
qrc_qml.cpp File Reference
Macros
#define QT_RCC_PREPEND_NAMESPACE(name) name
#define QT_RCC_MANGLE_NAMESPACE(name) name
Functions
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
int qInitResources_qml ()
int qCleanupResources_qml ()
Macro Definition Documentation
#define QT_RCC_MANGLE_NAMESPACE (name) name
#define QT_RCC_PREPEND_NAMESPACE (name) name
Referenced by qCleanupResources_qml(), and qInitResources_qml().
Function Documentation
int qCleanupResources_qml ()
References QT_RCC_PREPEND_NAMESPACE, and qUnregisterResourceData().
int qInitResources_qml ()
References qRegisterResourceData(), and QT_RCC_PREPEND_NAMESPACE.
bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qInitResources_qml().
bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qCleanupResources_qml().